# Generated by Django 3.2.5 on 2021-08-08 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sliderimg',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
