# Generated by Django 3.2.5 on 2021-08-08 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='test_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('title', models.CharField(max_length=255, null=True)),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='test_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('title', models.CharField(max_length=255, null=True)),
                ('body', models.TextField()),
            ],
        ),
    ]
