# Generated by Django 3.2.5 on 2021-08-07 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SlotBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, null=True)),
                ('email_field', models.EmailField(max_length=254, null=True)),
                ('phone_number', models.CharField(max_length=10, null=True)),
                ('geeks_field', models.TimeField(max_length=100, null=True)),
                ('body', models.TextField(max_length=100, null=True)),
            ],
        ),
    ]
