# Generated by Django 3.2.5 on 2021-08-04 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('field_name', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('geeks_field', models.TimeField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('field_name', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('geeks_field', models.TimeField(max_length=100)),
            ],
        ),
    ]
